In [5]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.12.0


In [6]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [7]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [8]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.53005856,  1.3444272 , -0.19838218,  0.44619808, -0.11979979,
         0.36667886,  0.09649207,  0.01721533,  0.10781243, -0.24308112]],
      dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.04474555, 0.29162765, 0.06234406, 0.1187771 , 0.06744085,
        0.10969781, 0.08372542, 0.07734423, 0.08467861, 0.05961871]],
      dtype=float32)

In [10]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
loss_fn(y_train[:1], predictions).numpy()

2.2100258

In [12]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [13]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


2023-03-27 13:31:00.963716: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


1875/1875 [==============================] - 29s 15ms/step - loss: 0.2963 - accuracy: 0.9136
Epoch 2/5
1875/1875 [==============================] - 27s 15ms/step - loss: 0.1416 - accuracy: 0.9580
Epoch 3/5
1875/1875 [==============================] - 28s 15ms/step - loss: 0.1088 - accuracy: 0.9675
Epoch 4/5
1875/1875 [==============================] - 31s 16ms/step - loss: 0.0869 - accuracy: 0.9734
Epoch 5/5
1875/1875 [==============================] - 31s 17ms/step - loss: 0.0728 - accuracy: 0.9768


In [14]:
model.evaluate(x_test,  y_test, verbose=2)

2023-03-27 13:33:27.866124: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 31360000 exceeds 10% of free system memory.


313/313 - 2s - loss: 0.0746 - accuracy: 0.9782 - 2s/epoch - 6ms/step


[0.0745638981461525, 0.9782000184059143]

In [15]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.6666106e-07, 1.3684680e-09, 1.0645736e-05, 9.9254023e-05,
        4.0820753e-11, 8.5345283e-07, 1.4072363e-15, 9.9988806e-01,
        6.2458739e-08, 3.0594569e-07],
       [7.4318823e-10, 1.0050851e-05, 9.9998975e-01, 6.4199128e-08,
        1.4899902e-17, 1.0023043e-07, 4.9823430e-09, 7.8477149e-14,
        1.8269308e-08, 3.0402482e-16],
       [1.2463414e-07, 9.9832505e-01, 6.7032391e-04, 1.1575792e-06,
        8.7650278e-06, 3.1432014e-06, 3.5206231e-05, 9.1808062e-04,
        3.8080118e-05, 1.2673553e-07],
       [9.9983883e-01, 4.2269643e-10, 2.1958453e-05, 1.0358460e-07,
        1.4676556e-07, 1.5107743e-06, 1.2941244e-04, 4.0742152e-06,
        1.4690475e-07, 3.7835491e-06],
       [1.3550482e-06, 8.1402778e-09, 1.9618519e-05, 5.7476461e-07,
        9.9837279e-01, 2.8376277e-07, 3.0240635e-05, 3.9304847e-05,
        4.5380616e-06, 1.5311813e-03]], dtype=float32)>